name: build and test

on: [push, pull_request]

jobs:

  job:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout repository and submodules
      uses: actions/checkout@v3.2.0
      with:
        submodules: recursive

    - uses: actions/setup-node@v3.5.1
      with:
        node-version: '18.x'

    - run: npm install

    - run: npm run lint

    - run: npm test
      env:
        CI: true
